version: "3.8"

services:
  backend-api:
    image: backend-api:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    pull_policy: never
    env_file:
      - .env
    build:
      context: backend
      dockerfile: api/Dockerfile.dev
      cache_from:
        - backend-api:latest
      args:
        - DEV_MODE=true
    container_name: backend-api
    volumes:
      - ./backend/:/code/
    command:
      - "uvicorn"
      - "quivr_api.main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
      - "--log-level"
      - "info"
    restart: always
    ports:
      - 5050:5050
      - 5678:5678 # debug port

  notifier:
    pull_policy: never
    image: backend-api:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    container_name: notifier
    volumes:
      - ./backend/:/code/
    command:
      - "python"
      - "/code/api/quivr_api/celery_monitor.py"
    restart: always
    depends_on:
      - redis
      - worker

  worker:
    pull_policy: never
    image: backend-worker:latest
    build:
      context: backend
      dockerfile: worker/Dockerfile.dev
      cache_from:
        - backend-worker:latest
      args:
        - DEV_MODE=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    container_name: worker
    volumes:
      - ./backend/:/code/
    command: "celery -A quivr_worker.celery_worker worker -l info"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 6379:6379

  beat:
    image: backend-api:latest
    pull_policy: never
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    container_name: beat
    command: celery -A quivr_api.celery_worker beat -l info
    volumes:
      - ./backend/:/code/
    restart: always
    depends_on:
      - redis

  flower:
    image: backend-api:latest
    pull_policy: never
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    container_name: flower
    command: celery -A quivr_api.celery_worker flower -l info --port=5555
    volumes:
      - ./backend/:/code/
    restart: always
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5555:5555
